config/routes.rb
Rails.application.routes.draw do

  root to: 'people#home'

  resources :people do 
    member do
      get 'set_user'
    end
  end

  get '/switch', to: 'people#switch'

  get '/search', to: 'people#search'


  resources :people do
    resources :addresses
    resources :hobbies
    resources :messages
  end
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :person
	validates_presence_of :street_address, :city, :state, :zip
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hobby.rb
class Hobby < ApplicationRecord
	belongs_to :person
	validates_presence_of :name
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :person
	validates_presence_of :content, :to
end

app/models/person.rb
class Person < ApplicationRecord
    has_many :hobbies, dependent: :destroy
    has_one :address, dependent: :destroy
    has_many :messages, dependent: :destroy
    validates_presence_of :name, :age, :gender

    @search_results = []
    @@user = ''

    def self.search(name, age, eye_color, hair_color, weight, height)
        @search_results = []
        if name || age || gender || eye_color || hair_color || height || weight
             name_results = Person.all.where(name: name) if name.blank? == false
            if age.blank? == false
                ages = []
                low_age = age.to_i - 5
                for i in 0..10 
                    ages  << "#{low_age + i}"
                end
            end
            age_results =  Person.all.where(age: ages) if age.blank? == false
            eye_color_results = Person.where(eye_color: eye_color) if eye_color.blank? == false
            hair_color_results = Person.where(hair_color: hair_color) if hair_color.blank? == false
            if weight.blank? == false
                weights = []
                low_weight = weight.to_i - 20
                for i in 0..40
                    weights << "#{low_weight + i}"
                end
            end
            weight_results = Person.where(weight: weights) if weight.blank? == false
            if height.blank? == false
                heights = []
                low_height = height.to_i - 4
                for i in 0..8
                    heights << "#{low_height + i}"
                end
            end
            height_results = Person.where(height: heights) if height.blank? == false
            name_results.to_a + age_results.to_a + eye_color_results.to_a + hair_color_results.to_a + weight_results.to_a + height_results.to_a
        end

    end

    def self.hair_color
        ['unspecified', 'blond', 'brown', 'black', 'red', 'grey', 'other']
    end

    def self.eye_color
        ['unspecified', 'blue', 'hazel', 'brown', 'grey', 'green', 'cat']
    end


    def self.gender
        ['female', 'male', 'transgender']
    end

    def self.set_user(id)
        @@user = Person.find(id)
    end

    def self.reset_user
        @@user = ''
    end

    def self.user
        @@user
    end





end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :person
  before_action :address, only: [:show, :edit, :update, :destroy]

  def index
    @address = @person.address
  end

  def show
  end

  def new
    @address = Address.new
  end

  def create
    @address = @person.address = Address.new(address_params)
    if @address.save
      redirect_to person_addresses_path(@person, @address)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @address.update(address_params)
      redirect_to person_address_path(@person, @address)
    else
      render :edit
    end
  end

  def destroy
    @address.destroy
    redirect_to person_addresses_path(@person)
  end

  private
    def address_params
      params.require(:address).permit(:street_address, :city, :state, :zip, :person_id)
    end

    def person
      @person = Person.find(params[:person_id])
    end

    def address
      @address = @person.address
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :person
  before_action :hobby, only: [:show, :edit, :update, :destroy]

  def index
    @hobbies = @person.hobbies
  end

  def show

  end

  def new
    @hobby = Hobby.new
  end

  def create
    @hobby = @person.hobbies.new(hobby_params)
    if @person.save
      redirect_to person_hobbies_path(@person, @hobby)
    else
      render :new
    end
  end

  def edit

  end

  def update

    if @hobby.update(hobby_params)
      redirect_to person_hobby_path(@person, @hobby)
    else
      render :edit
    end
  end

  def destroy
    @hobby.destroy
    redirect_to person_hobbies_path(@person)
  end

  private
    def hobby_params
      params.require(:hobby).permit(:name, :description)
    end

    def person
      @person = Person.find(params[:person_id])
    end

    def hobby
      @hobby = @person.hobbies.find(params[:id])

    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :person, only: [:show, :edit, :update, :destroy]

  def home
    @people = Person.all
    @user = Person.user
  end

  def switch
    @user = Person.reset_user
    redirect_to root_path
  end

  def set_user
    @user = Person.set_user(params[:id])
    redirect_to root_path
  end

  def index
    @people = Person.all
  end

  def show

  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      Person.set_user(@person)
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  def edit

  end

  def update

    if @person.update(person_params)
      redirect_to person_path(@person)
    else
      render :edit
    end
  end

  def destroy
    @person.destroy
    @user = Person.reset_user
    redirect_to root_path
  end

  def search
    @people = Person.all
    @search = Person.search(params[:name], params[:age], params[:eye_color], params[:hair_color], params[:weight], params[:height])
  end

  private
    def person_params
      params.require(:person).permit(:name, :gender, :hair_color, :eye_color, :age, :weight, :height)
    end

    def person
      @person = Person.find(params[:id])
    end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_form.html.erb
<%= form_for [@person, @address] do |f| %>
  <%= f.label :street_address %>
  <%= f.text_field :street_address, required: true %>
  <br/>
  <%= f.label :city %>
  <%= f.text_field :city, required: true %>
  <br/>
  <%= f.label :state %>
  <%= f.select :state, %w(AK AL AR AZ CA CO CT DC DE FL GA HI IA ID IL IN KS KY LA MA MD ME MI MN MO MS MT NC ND NE NH NJ NM NV NY OH OK OR PA RI SC SD TN TX UT VA VT WA WI WV WY), required: true %>
  <br/>
  <%= f.label :zip %>
  <%= f.number_field :zip, required: true %>
  <br/>
  <%= f.submit %>
<% end %>

<%= link_to "Person profile", person_path(@person) %>

app/views/addresses/edit.html.erb
<h1> Edit Address for <%= @person.name %> </h1>

<%= render(partial: 'form') %>

app/views/addresses/index.html.erb
<h1><%= @person.name%>'s Address is:</h1>

<% if @address.blank? %>
	<h3> No address listed</h3>
	<% if @person == Person.user %>
  		<%= link_to 'Add Address', new_person_address_path(@person) %>
  	<% end %>
<% else %>
   <h3> <%= @address.street_address %> </h3>
   <h3> <%= @address.city + ", " + @address.state %>
   <h3> <%= @address.zip %> </h3>
   <% if @person == Person.user %>
<%= link_to "Edit", edit_person_address_path(@person, @address) %>
<br/>
<%= link_to 'DELETE', person_address_path(@person, @address), method: :delete, data: {confirm: 'Are You Sure?'}%>
	<% end %>
<% end %>
<br/>
<%= link_to 'Full profile', person_path(@person) %>

app/views/addresses/new.html.erb
<h1> Set Address for <%= @person.name %> </h1>

<%= render(partial: 'form') %>

app/views/addresses/show.html.erb
<h1><%= @person.name%>'s Address is:</h1>

<% if @address.blank? %>
<h3> No address. Please add an address </h3>
  <%= link_to 'Add Address', new_person_address_path(@person) %>
<% else %>
   <h3> <%= @address.street_address %> </h3>
   <h3> <%= @address.city + ", " + @address.state %>
   <h3> <%= @address.zip %> </h3>
<% if @person == Person.user %>
	<%= link_to "Edit", edit_person_address_path(@person, @address) %>
	<br/>
	<%= link_to 'DELETE', person_address_path(@person, @address), method: :delete, data: {confirm: 'Are You Sure?'}%>
	<% end %>
<% end %>
<br/>
<%= link_to 'Full profile', person_path(@person) %>

app/views/hobbies/_form.html.erb
<%= form_for [@person, @hobby] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <br />
  <%= f.label :description %>
  <%= f.text_field :description, required: true %>
  
  <br />
  <%= f.submit %>
<% end %>
<%= link_to "All hobbies", person_hobbies_path(@person) %>

app/views/hobbies/edit.html.erb
<h1> Editing: <%= @hobby.name %> </h1>

<%= render(partial: 'form') %>

app/views/hobbies/index.html.erb
<h1> <%= @person.name %> - All Hobbies </h1>

<% if @hobbies.any? %>
  <!-- loop the Hobbies and display them -->
  <ul>
    <% @hobbies.each do |hobby| %>
      <li> <%= hobby.name %> - <%= link_to 'Description', person_hobby_path(@person, hobby) %> 
      <% if @person == Person.user %>
      	<%= link_to 'Delete', person_hobby_path(@person, hobby), method: :delete, data: {confirm: 'Are You Sure?'} %>
      	<%= link_to 'Edit', edit_person_hobby_path(@person, hobby) %>
      	</li>
      <% end %>
    <% end %>
  </ul>
<% else %>
  <!-- display no hobbies message -->
  <h3>No hobbies listed</h3>
<% end %>
<% if @person == Person.user %>
	<%= link_to 'New hobby', new_person_hobby_path(@person) %>
<% end %>
<%= link_to  'Full profile', person_path(@person) %>

app/views/hobbies/new.html.erb
<h1>Create A New Hobbie For: <%= @person.name %> </h1>

<%= render(partial: 'form') %>

app/views/hobbies/show.html.erb
<h1> <%= @hobby.name %> </h1>

<!-- Description -->
<p> Description: <%= @hobby.description %> </p>
<% if @person == Person.user %>
	<%= link_to "Edit" , edit_person_hobby_path(@person, @hobby) %>
	<%= link_to 'Delete', person_hobby_path(@person, @hobby), method: :delete, data: {confirm: 'Are You Sure?'} %>
<% end %>
<br>
<%= link_to "All hobbies", person_hobbies_path(@person) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DatingApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo right">Love by RDB</a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Search', search_path %> </li>
        <% if Person.user.blank? == false %>
        <li class="center-align"> <%= link_to 'Profile', person_path(Person.user) %></li>
        <% end %>
      </ul>
    </div>
  </nav>
<%= yield %>

</body>
</html>

app/views/messages/edit.html.erb
<h1>Messages#edit</h1>
<p>Find me in app/views/messages/edit.html.erb</p>

app/views/messages/index.html.erb
<h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>

app/views/messages/new.html.erb
<h1>Messages#new</h1>
<p>Find me in app/views/messages/new.html.erb</p>

app/views/messages/show.html.erb
<h1>Messages#show</h1>
<p>Find me in app/views/messages/show.html.erb</p>

app/views/people/_form.html.erb
<% if @person.errors.any? %>
  <ul>
    <% @person.errors.full_messages.each do |error| %>
      <li> <%= error %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_for @person do |f| %>
  <div class='input-field'>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <br />

  <div class='input-field'>
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <br />

  <div class='input-field'>
  <%= f.label :weight %>
  <%= f.number_field :weight %>
  </div>

  <br />

  <div class='input-field'>
    <%= f.label :height %>
    <%= f.number_field :height %> 
  </div>

  <br>

  <div class='input-field'>
    <%= f.label :gender, class: 'active' %>
    <%= f.select :gender, Person.gender, {}, {}%>
  </div>

  <br />

  <div class='input-field'>
    <%= f.label :hair_color, class: 'active' %>
    <%= f.select :hair_color, Person.hair_color, {}, {} %>
  </div>

  <br />

  <div class='input-field'>
    <%= f.label :eye_color, class: 'active' %>
    <%= f.select :eye_color, Person.eye_color, {}, {} %>
  </div>

  <br />
  <div class='row' >
  <%= f.submit 'Update', class: 'btn pull-left col s6 m2' %>
<% end %>

<%= link_to "All people", people_path, class: 'btn pull-left col s6 m2' %>
</div>

app/views/people/_search_results.html.erb
<% if @search.any? %>
 <ul>
   <% @search.each do |result| %>
     <li>
      <%= link_to result.name, person_path(result) %>
     </li>
   <% end %>
 </ul>

<% else %>
  <p> No search results </p>
  
  <!-- Empty array, no people in DB -->
<% end %>

app/views/people/edit.html.erb
<h1> Editing: <%= @person.name %> </h1>

<%= render(partial: 'form') %>

app/views/people/home.html.erb
<h1 class="z-depth-1 col s12 center-align">Find true love!</h1>

<% if @user.blank? %>

<h2> Please tell us who you are. </h2>

<% if @people.any? %>
 <ul>
   <% @people.each do |person| %>
     <li>
      <%= link_to person.name, set_user_person_path(person) %>
     </li>
   <% end %>
 </ul>

<% else %>
  <p> Nobody is here, create a person: </p>
  
  <!-- Empty array, no people in DB -->
<% end %>

<% else %>
<row class='row'>
<h2 class='col s12 m'> Welcome <%= @user.name %>! </h2>
<div>Personal profile options:</div>
<%= link_to 'Edit', edit_person_path(@user) %> <%= link_to 'Delete', person_path(@user), method: :delete, data: {confirm: 'Are You Sure?'} %> <%= link_to 'View profile', person_path(@user) %>
</div>
<h3>Who would you like to view?</h3>

<% if @people.any? %>
 <ul>
   <% @people.each do |person| %>
      <% if person != Person.user %>
     <li>
      <%= link_to person.name, person_path(person) %>
     </li>
    <% end %>
  <% end %>
 </ul>

<%= link_to 'Switch Profile', switch_path %> 

<% else %>
  <p> Nobody is here, create a profile!: </p>
  
  <!-- Empty array, no people in DB -->
<% end %>
<% end %>

<%= link_to 'Create Profile', new_person_path %>

app/views/people/index.html.erb
<h1>All People</h1>

<% if @people.any? %>
 <ul>
   <% @people.each do |person| %>
   	<% if person != Person.user %>
     	<li>
      	<%= link_to person.name, person_path(person) %>
     	</li>
   	<% end %>
   <% end %>
 </ul>

<% else %>
  <p> Nobody is here, create a person: </p>
  
<% end %>

app/views/people/new.html.erb
<h1> Create a person! </h1>

<%= render(partial: 'form') %>

app/views/people/search.html.erb
<h1 class="center-align">Search</h1>
<div class="container">
	<%= form_tag("/search", method: "get") do %>
		<div class='row'>
			<div class='input-field col s12 m4' ><%= label_tag(:name, "Name") %>
				<%= text_field_tag :name, params[:name] %> </div>
				<br/>
			<div class='input-field col s12 m4' ><%= label_tag(:age, "Age") %>
				<%= number_field_tag :age, params[:age] %> </div>
				<br/>
			<div class='input-field col s12 m4' ><%= label_tag(:weight, "Weight") %>
				<%= number_field_tag :weight, params[:weight] %> </div>
				<br/>
			<div class='input-field col s12 m4' ><%= label_tag(:height, "Height (inches)") %>
				<%= number_field_tag :height, params[:height] %> </div>
				<br/>
			<div class='input-field col s12 m4' ><%= label_tag(:eye_color, "Eye Color") %>
				<%= text_field_tag :eye_color, params[:height]%> </div>
				<br/>
			<div class='input-field col s12 m4' ><%= label_tag(:hair_color, "Hair Color") %>
				<%= text_field_tag :hair_color, params[:hair_color] %> </div>
				<br/>
			<div class='col s12'> <%= submit_tag "Search", class: 'btn' %> </div>

		</div>
	<% end %>
</div>
<br>

<div class='center-align'>
<% if Person.user.blank? == false %>
	<% if @search %>
	<h3>Your search results:</h3>
		<div class='row'>
		<% @search.each do |result| %>
			<% if result != Person.user && Person.user.gender != result.gender %>
			<span class="card-panel hoverable col s12 m4 l3 center-align" >
			<%= link_to result.name, person_path(result)%>
			</span>
			<% end %>
		<% end %>
		</div>
		<% @search = [] %>
	<% end %>
	<% else %>
		<h5>Choose or create a profile to see results!</h5>
<% end %>

<%= link_to 'All people', people_path %>
</div>

app/views/people/show.html.erb
<h1> Info For Person: <%= @person.name %> </h1>

<table>
  <thead>
    <tr>
      <th>|  Age  </th>
      <th>|  Gender  </th>
      <th>|  Hair Color  </th>
      <th>|  Eye Color  </th>
      <th>|  Weight   </th>
      <th>|  Height  </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td> <%= @person.age %> </td>
      <td> <%= @person.gender %> </td>
      <td> <%= @person.hair_color %> </td>
      <td> <%= @person.eye_color %> </td>
      <td> <%= @person.weight %> </td>
      <td> <%= @person.height %> </td>
    </tr>
  </tbody>
</table>


<%= link_to "#{@person.name}'s address", person_addresses_path(@person) %>
<br>
<%= link_to "#{@person.name}'s hobbies", person_hobbies_path(@person) %>
<br/>
<%= link_to 'All People', people_path %>
<br><br>
<% if Person.user == @person %>
<%= link_to 'Edit', edit_person_path(@person) %>

<%= link_to 'Delete', person_path(@person), method: :delete, data: {confirm: 'Are You Sure?'} %>
<% end %>